### ISSUE TITLE
Checkout fields aren't stored in session during checkout.

### ISSUE THREAD

**Issue by messica** [Kendysond/Wordpress-Paid-Membership-Pro-Paystack#11]
Normally PMPro stores user fields and custom fields added with Register Helper in session variables while the user is redirected to the gateway to complete payment for offsite gateways like PayPal Express and Paystack. It doesn't look like Paystack is doing this, which is causing issues for some support users.

See https://github.com/strangerstudios/paid-memberships-pro/blob/dev/classes/gateways/class.pmprogateway_paypalexpress.php#L227-L267

**Comment by steveamaza** [comment]
Hey @messica thanks for pointing this out. Can you help provide some more colour on this? In our case what user/custom fields will need to be saved? We don't have usernames and passwords like in the case of PayPal Express.

Also what issues has it caused so far?

**Comment by larebsyed** [comment]
@messica & @steveamaza I have fixed this issue in my PR. Please review if you get time thanks
