### ISSUE TITLE
My paystack gateway for paid membership pro plugin has stopped working

### ISSUE THREAD

**Issue by dgene** [Kendysond/Wordpress-Paid-Membership-Pro-Paystack#19]
Good evening. Please I need help with the plugin. It was working for a while but later it just stopped since a week now. Clicking on the “checkout with paystack” button doesn’t bring out the paystack pop up anymore. It just keeps loading till an error comes up with a blank page. Please how can I resolve it?

**Comment by andrewlimaza** [comment]
This is resolved with the latest versions. @dgene Please let us know if you run into any further issues.
