### ISSUE TITLE
Page is not loading

### ISSUE THREAD

**Issue by Surayyah** [Kendysond/Wordpress-Paid-Membership-Pro-Paystack#2]
Hello there, I have this plugin for paid membership pro, it was working initially but then all of a sudden it stopped and does goes to an empty page instead of going to paystack. URL : feedtheneedycharity.com. If you may please check this for me

**Comment by ibrahimlawal** [comment]
@Surayyah please check error logs on your server for technical information about the failure and share so we may diagnose.
