### ISSUE TITLE
Checking out on a daily subscription membership level creates a weekly subscription plan within Paystack and a Weekly plan does not get created within Paystack

### ISSUE THREAD

**Issue by MaryOJob** [Kendysond/Wordpress-Paid-Membership-Pro-Paystack#34]
Steps to recreate this issue:

- Set up a test site, add Paystack test keys to PMPro Getaway setup and Payments tab, set Paystack as the default getaway and set environment to testing.
- Set up a recurring level within PMPro, with an initial amount of NGNX, and billing amount of NGNX, per (X) Days, and no limit
- Set up a recurring level within PMPro, with an initial amount of NGNX, and billing amount of NGNX, per (X) Week, and no limit
- The level with daily recurring setup gets a plan created in Paystack but set to weekly
- The level with weekly recurring setup does not get a plan created in Paystack at all

Tested this on a live site, testing environment and on a local site, same behavior.

**Comment by MaryOJob** [comment]
One more thing please, the test checkouts on the live site, all subscriptions got cancelled like three hours ago, under plans in Paystack, they all show completed. I did not cancel any of these subscriptions.

**Comment by MaryOJob** [comment]
@steveamaza Boss can we get some eyes on this, please?

**Comment by andrewlimaza** [comment]
This is fixed in the latest `dev` branch with this commit - https://github.com/PaystackOSS/plugin-paid-membership-pro/commit/cd422f461c49dbe7aee6ef7b523adae7e85201b1

It supports: daily, weekly, monthly, quarterly (set PMPro to 3 month cycle), biannually (set PMPro to 6 month cycle) and annually.
