### ISSUE TITLE
Currency and Tax Settings not always visible on payment settings page.

### ISSUE THREAD

**Issue by ipokkel** [Kendysond/Wordpress-Paid-Membership-Pro-Paystack#41]
The "Currency and Tax Settings" were hidden when the "Gateway Environment" option was set to "Sandbox/Testing". 

To display these fields was achieved by temporarily changing  the "Gateway Environment" option to "Live/Production" and back to "Sandbox/Testing". Once this was done these fields remained visible. 

![2023-09-01_14-45-00](https://github.com/PaystackOSS/plugin-paid-membership-pro/assets/9744519/d1237cc5-0c23-487a-93eb-4ac145155017)

**Comment by andrewlimaza** [comment]
I haven't been able to consistently replicate this but I am looking into it.

**Comment by andrewlimaza** [comment]
I've done a fresh install and unable to reproduce this. I'm going to close this for now as I believe PMPro core handles this and maybe something was weird.

I'll reopen this if the issue persists or we can get exact steps to replicate.

Thanks @ipokkel
