### ISSUE TITLE
blank checkout page

### ISSUE THREAD

**Issue by phaybours** [Kendysond/Wordpress-Paid-Membership-Pro-Paystack#7]
I am using this plugin as payment option for paid membership pro but after filling the registration details, and making attempt to check out with  paystack by clicking the button with "Check out with paystack", the page returned was blank. Kindly help me on how to resolve this issue.

**Comment by steveamaza** [comment]
Hey @phaybours this should be your server is unable to communicate with Paystack servers on account of not meeting minimal requirements. For more information, see https://developers.paystack.co/blog/tls-v12-requirement.

Please reach out to your hosting provider to find out if that's the case. If yes, they will need to have your server's version of OpenSSL to a more recent version

**Comment by phaybours** [comment]
thanks for your quick response @steveamaza. will contact them and revert.

**Comment by phaybours** [comment]
@steveamaza I have checked the tls version and it is actually version 1.2 but I am still experiencing the same challenge. see  the screen shot from browser  below
![sshot](https://user-images.githubusercontent.com/41201323/42721103-f8176c32-872b-11e8-80fe-7626f2f7c650.png)
but the checkout page is still coming out blank

**Comment by steveamaza** [comment]
Hi @phaybours, I think this might be a situation where a user agent is not being sent with the requests from your server. Can you please respond to the last email you sent so I can investigate further?

**Comment by phaybours** [comment]
Sorry Stephen for not responding quick. I've been busy on a project.

Still trying to get feed back from my hosting company. Will get back to you
as soon as they reply.

Regards
